### ISSUE TITLE
Language/framework support

### ISSUE THREAD

**Issue by sidot3291** [clerkinc/local-compose#8]
### Frontend
- [x] Create react app

### Javascript
- [x] Express

### Python
- [x] Django
- [x] Flask

### Ruby
- [x] Rails
- [x] Sinatra

**Comment by burrows-labs** [comment]
Windows Ruby with devkit keeps failing an integrity check.

![Screenshot](https://user-images.githubusercontent.com/586011/60855649-949c8300-a1d2-11e9-9e83-7e238481998a.png)

If we do an out-of-band installation of msys2, we need to play nice with the detection algorithm in ridk.
https://github.com/oneclick/rubyinstaller2/blob/master/lib/ruby_installer/build/msys2_installation.rb#L32
